= OpenShift Hybridizer
include::_attributes.adoc[]

The https://www.ansible.com[Ansible] scripts that can be used to provision an **Hybrid Cloud Environment** and generate the required https://www.ansible.com[Ansible] scripts to deploy **All In One** OpenShift cluster on to it.

[IMPORTANT]
=====
Currently supported **Cloud Providers**:

* Azure(**azr**)
* Amazon(**aws**) 
* Google Cloud Platform (**gcp**)

Supports only OpenShift 3.10 or above 
=====

== Sources

The sources of these scripts can be downloaded from  {uri-repo}#[GitHub].

Lets clone the sources `git clone {uri-repo}` to a directory on local file system.  For convenience we shall refer to the sources clone directory as `$PROJECT_HOME`.

== Pre-Requisites

* `Docker` installed and available locally, based on your environment have native docker for linux or https://docs.docker.com/docker-for-mac/[Docker for Mac] or https://docs.docker.com/docker-for-windows/[Docker for Windows] installed

* Refer to the following documentation on what are the pre-requisites for each Cloud Provider that are currently supported:

** AWS   - https://docs.ansible.com/ansible/2.5/scenario_guides/guide_aws.html

** Azure - https://docs.ansible.com/ansible/2.5/scenario_guides/guide_azure.html

** Google Cloud Platform -   
   https://docs.ansible.com/ansible/2.5/scenario_guides/guide_gce.html

[[container-installer]]
== Installer Image

The installer image is built from {uri-ansible}[Ansible Runner] with need Ansible Cloud modules which are required to provision the cloud resources. The provisioned Cloud resources can then be used to deploy **All In One** OpenShift cluster.

The installer image is available at `{uri-docker-hca}`, to pull it run the command:

[source,sh,subs=attributes+]
----
$ docker pull {uri-docker-hca}
----

== Create Hybrid Cloud Instances

=== Preparation 

Rename `$PROJECT_HOME/env/extravars.example` to `$PROJECT_HOME/env/extravars`, this file will be used to configure your cloud keys and other ansible facts. 

The following Cloud Provider specific sections will detail more on the variables that can defined in `extravars`.

NOTE: The `$PROJECT_HOME/env/extravars` follows YAML convention.

==== Variables

[cols=".<1,.<4,.<4,<5"]
|===
| Name |Description |  Default value |  Example

| clouds | The public cloud(s)where to provision| Currently supported values are azr, aws and gcp.
a| 
[source,yaml]
----
clouds:
 - gcp
 - azr
 - aws
----

The example configures provisioning of three clouds: AWS, Azure and Google Cloud Platform

|instance_name | The compute instance name that will be assigned |  openshift-all-in-one |  

|gcp_rollback | Delete all Google Cloud Platform resources that were provisioned  |  False |  

|azure_rollback | Delete all Azure resources that were provisioned  |  False | 

|aws_rollback | Delete all Amazon Web Services resources that were provisioned  |  False | 

|===